force-app/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <description>Links sales profile with the certification rating answers provided by the manager</description>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification__c/fields/Sales_Rep_Profile__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the sales rep profile for which the certification is created</description>
    <label>Sales Rep Profile</label>
    <referenceTo>Sales_Rep_Profile__c</referenceTo>
    <relationshipName>Certifcations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification__c/fields/Total_Quantitative_Weight__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantitative_Weight__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total weight of the quantitative ratings for the most recent cycle</description>
    <label>Total Quantitative Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Answer__c/Certification_Answer__c.object-meta.xml
<CustomObject>
    <description>Used to store the ratings given to the sales rep</description>
    <label>Certification Answer</label>
    <nameField>
        <label>Certification Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification_Answer__c/fields/Certifcation__c.field-meta.xml
<CustomField>
    <fullName>Certifcation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the reference to the Certification record that the answer is related to</description>
    <label>Certification</label>
    <referenceTo>Certification__c</referenceTo>
    <relationshipLabel>Certification Answers</relationshipLabel>
    <relationshipName>Certification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification_Answer__c/fields/Certifcation_Rating__c.field-meta.xml
<CustomField>
    <fullName>Certifcation_Rating__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the reference of the rating/question</description>
    <label>Certification Rating</label>
    <referenceTo>Certification_Rating__c</referenceTo>
    <relationshipLabel>Certification Answers</relationshipLabel>
    <relationshipName>Certification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification_Answer__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>The date before which the answer should be updated</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification_Answer__c/fields/Escalation_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Email_Date__c</fullName>
    <description>The date on which an escalation email should be sent to the manager</description>
    <label>Escalation Email Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification_Answer__c/fields/Manager_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Manager_Email_Date__c</fullName>
    <description>The date on which email should be triggered to the manager</description>
    <label>Manager Email Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification_Answer__c/fields/Rating_Score__c.field-meta.xml
<CustomField>
    <fullName>Rating_Score__c</fullName>
    <description>Stores the score given by the manager</description>
    <label>Certification Score</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Answer__c/fields/Rating_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Rating_Start_Date__c</fullName>
    <description>The date from which the manager can start rating the rep</description>
    <label>Rating Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Certification_Answer__c/fields/Sales_Rep_Profile__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the sales profile the answer record is associated with</description>
    <label>Sales Rep Profile</label>
    <referenceTo>Sales_Rep_Profile__c</referenceTo>
    <relationshipLabel>Certification Answers</relationshipLabel>
    <relationshipName>Certification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/Certification_Rating__c.object-meta.xml
<CustomObject>
    <description>Object used to store the certification question</description>
    <label>Certification Rating</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification_Rating__c/fields/Assessment_type__c.field-meta.xml
<CustomField>
    <fullName>Assessment_type__c</fullName>
    <description>Indicates if the rating is qualitative or quantitative</description>
    <label>Assessment type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualitative</fullName>
            </value>
            <value>
                <fullName>Quantitative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Deactivated__c.field-meta.xml
<CustomField>
    <fullName>Deactivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this rating should not appear for the certifications that are created in future</description>
    <label>Deactivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>Store the API name for the Quantitative rating</description>
    <label>Field Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Numeric_Weight__c.field-meta.xml
<CustomField>
    <fullName>Numeric_Weight__c</fullName>
    <description>Store the Numeric Value of picklist</description>
    <formula>VALUE(TEXT( Weight__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numeric Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Roles_enabled__c.field-meta.xml
<CustomField>
    <fullName>Roles_enabled__c</fullName>
    <description>Stores the list of sales profile roles for which the certification is active</description>
    <label>Roles enabled</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Timing__c.field-meta.xml
<CustomField>
    <fullName>Timing__c</fullName>
    <defaultValue>&quot;Week&quot;</defaultValue>
    <description>The number of days within which the rating should be completed</description>
    <label>Timing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End of month</fullName>
            </value>
            <value>
                <fullName>End of quarter</fullName>
            </value>
            <value>
                <fullName>Bi-annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Stores if the sales rep is new/tenured</description>
    <label>Assign to onboarded reps?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>Tenured</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X0LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X0LevelHigh__c</fullName>
    <label>0LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X0LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X0LevelLow__c</fullName>
    <label>0LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X1LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X1LevelHigh__c</fullName>
    <label>1LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X1LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X1LevelLow__c</fullName>
    <label>1LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X2LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X2LevelHigh__c</fullName>
    <label>2LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X2LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X2LevelLow__c</fullName>
    <label>2LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X3LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X3LevelHigh__c</fullName>
    <label>3LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X3LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X3LevelLow__c</fullName>
    <label>3LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X4LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X4LevelHigh__c</fullName>
    <label>4LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X4LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X4LevelLow__c</fullName>
    <label>4LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification_Setting__c/Notification_Setting__c.object-meta.xml
<CustomObject>
    <label>Notification Setting</label>
    <nameField>
        <label>Notification Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Setting__c/fields/Advance_Reminders__c.field-meta.xml
<CustomField>
    <fullName>Advance_Reminders__c</fullName>
    <label>Advance Notice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 days prior</fullName>
            </value>
            <value>
                <fullName>7 days prior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Setting__c/fields/Enable_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Enable_Notifications__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Notifications</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Setting__c/fields/Escalation__c.field-meta.xml
<CustomField>
    <fullName>Escalation__c</fullName>
    <label>Escalation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2 days overdue</fullName>
            </value>
            <value>
                <fullName>7 days overdue</fullName>
            </value>
            <value>
                <fullName>10 days overdue</fullName>
            </value>
            <value>
                <fullName>Never</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Setting__c/fields/Notification_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Notification_Frequency__c</fullName>
    <label>Notification Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Every Other Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

funnelocity/src/objects/Sales_Rep_Profile__c.object
<CustomObject>
    <description>Object used to store the details of every person in the sales team</description>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/Rep_Staus__c.field-meta.xml
<CustomField>
    <fullName>Rep_Staus__c</fullName>
    <label>Onboarded?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>Tenured</fullName>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Lists the roles in the funnelocity app</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Executive</fullName>
        <label>Account Executive - Hunter</label>
    </customValue>
    <customValue>
        <fullName>Sales Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Operations Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Manager&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>VP</fullName>
    </customValue>
    <customValue>
        <fullName>Continent VP of Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Country VP of Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>SVP of Sales</fullName>
    </customValue>
    <description>Used for the Funnelocity app custom roles</description>
    <masterLabel>Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FunnelCreateCertAnswers_Controller.cls
/*
Copyright: Funnel Metrics, LLC
*/
public with sharing class FunnelCreateCertAnswers_Controller{
    
    public static void deleteAndCreateCertAnswers(Set<Id> deleteList, Set<Id> createList){        
        
        if(deleteList != null && deleteList.size() > 0){
        
            List<Certification__c> deleteCerts = [SELECT id FROM Certification__c WHERE Sales_Rep_Profile__c IN : deleteList];
            
            //List<Certification_Answer__c> ansList = [SELECT Id, Certifcation__c, Rating_Score__c FROM Certification_Answer__c WHERE Rating_Score__c = null AND Certifcation_Rating__r.Assessment_type__c='Qualitative' AND Certifcation__c IN :deleteCerts];        
            List<Certification_Answer__c> ansList = [SELECT Id, Certifcation__c, Rating_Score__c FROM Certification_Answer__c WHERE Due_Date__c >= Today AND Certifcation_Rating__r.Assessment_type__c='Qualitative' AND Certifcation__c IN :deleteCerts];
            system.debug(' deleted ans '+ansList);
            
            //if(Schema.sObjectType.Certification_Answer__c.isDeletable()){ 
                DELETE ansList;
            //}
        }
        
        List<Certification__c> certs = [SELECT id, Sales_Rep_Profile__r.Rep_Staus__c, Sales_Rep_Profile__r.Role__c FROM Certification__c WHERE Sales_Rep_Profile__c IN : createList];
        
        Integer noOfDays = Date.daysInMonth(Date.today().year(),Date.today().month());
        
        Notification_Setting__c ns = [SELECT Id, Enable_Notifications__c, Advance_Reminders__c, Notification_Frequency__c, Escalation__c FROM Notification_Setting__c LIMIT 1];
        
        List<Certification_Answer__c> createAnsRecords = new List<Certification_Answer__c>();

        //Creating certification answers for monthly ratings
        List<Certification_Rating__c> certiRating = [SELECT Id, X0LevelHigh__c, X0LevelLow__c,X1LevelHigh__c,X1LevelLow__c,X2LevelHigh__c,X2LevelLow__c,
                                                 X3LevelHigh__c,X3LevelLow__c,X4LevelHigh__c,X4LevelLow__c,Deactivated__c,Roles_enabled__c,Numeric_Weight__c,
                                                 Field_Name__c,name,User_Type__c  FROM Certification_Rating__c where Assessment_type__c='Qualitative' 
                                                 AND Deactivated__c = false And Timing__c='End of month' ];        
            
        if(certiRating != null && certiRating.size() > 0 ){                            
              
              for(Certification__c s: certs){
                  system.debug(' s '+s);                  
                  for(Certification_Rating__c cr : certiRating){
                      
                      system.debug(' cr '+cr); 
                      
                      Set<String> rolesSet = new Set<String>();
                    
                      if(cr.Roles_enabled__c != null){
                            List<String> rolesList = cr.Roles_enabled__c.split(';');
                            for(String r:rolesList){
                                rolesSet.add(r);
                            }
                      }
                                            
                      if(cr.Roles_enabled__c != null  && (s.Sales_Rep_Profile__r.Rep_Staus__c == cr.User_Type__c  || cr.User_Type__c =='Both') && s.Sales_Rep_Profile__r.Role__c != null && rolesSet.contains(s.Sales_Rep_Profile__r.Role__c)){
                          
                          system.debug(' condition matched ');
                          
                          Certification_Answer__c ca= new Certification_Answer__c();
                          ca.Name = cr.name;
                          ca.Certifcation__c = s.id;
                          ca.Certifcation_Rating__c = cr.id;
                          ca.Sales_Rep_Profile__c=s.Sales_Rep_Profile__c;                                                    

                          ca.Due_Date__c = Date.newInstance(Date.today().year(),Date.today().month(),noOfDays);
                          ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-7);
                          
                          if(ns.Enable_Notifications__c ){
                          
                                if(ns.Advance_Reminders__c == '1 day prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-1);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-1);
                                }
                                else if(ns.Advance_Reminders__c == '3 days prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-3);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-3);
                                }
                                else if(ns.Advance_Reminders__c == '7 days prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-7);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-7);
                                }
                                
                                if(ns.Escalation__c == '2 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 2;
                                }
                                else if(ns.Escalation__c == '7 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 7;
                                }
                                else if(ns.Escalation__c == '10 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 10;
                                }
                          }
                    
                          createAnsRecords.add(ca);                                          
                          
                      }
                                                                
                  }
                                    
              }
              
        } 
        
        //Creating certification answers for quarterly ratings
        /*DateTime quarterEnd = FunnelCalculationHelper.getQuarterEndDate(Date.today());
        system.debug(' quart end date '+quarterEnd);    
        Date quarterEndDate = Date.newInstance(quarterEnd.yearGmt(), quarterEnd.monthGmt(),quarterEnd.dayGmt());
        
        DateTime quarStartDateTime = FunnelCalculationHelper.getQuarterStartDate();
        quarStartDateTime = quarStartDateTime.addMonths(2);
                        
        noOfDays = Date.daysInMonth(quarStartDateTime.year(),quarStartDateTime.month());
                       
        Date dueDate = Date.newInstance(quarStartDateTime.year(),quarStartDateTime.month(),noOfDays);*/
        
        Date dueDate = FunnelCalculationHelper.getQuarterEndInDateFormat(Date.today());
           
        certiRating = [SELECT Id, X0LevelHigh__c, X0LevelLow__c,X1LevelHigh__c,X1LevelLow__c,X2LevelHigh__c,X2LevelLow__c,
                         X3LevelHigh__c,X3LevelLow__c,X4LevelHigh__c,X4LevelLow__c,Deactivated__c,Roles_enabled__c,Numeric_Weight__c,
                         Field_Name__c,name,User_Type__c  FROM Certification_Rating__c where Assessment_type__c='Qualitative' 
                         AND Deactivated__c = false And Timing__c='End of quarter' ];        
            
        if(certiRating != null && certiRating.size() > 0 ){
            
              for(Certification__c s: certs){
                                    
                  for(Certification_Rating__c cr : certiRating){                  
                      
                      Set<String> rolesSet = new Set<String>();
                    
                      if(cr.Roles_enabled__c != null){
                            List<String> rolesList = cr.Roles_enabled__c.split(';');
                            for(String r:rolesList){
                                rolesSet.add(r);
                            }
                      }
                                            
                      if(cr.Roles_enabled__c != null  && (s.Sales_Rep_Profile__r.Rep_Staus__c == cr.User_Type__c  || cr.User_Type__c =='Both') && s.Sales_Rep_Profile__r.Role__c != null && rolesSet.contains(s.Sales_Rep_Profile__r.Role__c)){                      
                          
                          system.debug(' condition matched ');
                          
                          Certification_Answer__c ca= new Certification_Answer__c();
                          ca.Name = cr.name;
                          ca.Certifcation__c = s.id;
                          ca.Certifcation_Rating__c = cr.id;
                          ca.Sales_Rep_Profile__c=s.Sales_Rep_Profile__c;                                                    

                          ca.Due_Date__c = dueDate;
                          ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-7);
                          
                          if(ns.Enable_Notifications__c ){
                          
                                if(ns.Advance_Reminders__c == '1 day prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-1);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-1);
                                }
                                else if(ns.Advance_Reminders__c == '3 days prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-3);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-3);
                                }
                                else if(ns.Advance_Reminders__c == '7 days prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-7);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-7);
                                }
                                
                                if(ns.Escalation__c == '2 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 2;
                                }
                                else if(ns.Escalation__c == '7 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 7;
                                }
                                else if(ns.Escalation__c == '10 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 10;
                                }
                          }
                    
                          createAnsRecords.add(ca);                                          
                          
                      }
                                                                
                  }
                                    
              }
                            
        } 
        
        //Creating certification answers for bi-annual ratings
        
        DateTime Fyear = FunnelTriggerBatchHelper.getFiscalYearDate('Current_Year');
                
        DateTime month6Start = Fyear.addMonths(5);
        
        noOfDays = Date.daysInMonth(month6Start.yearGMT(),month6Start.monthGMT());
        
        dueDate = Date.newInstance(month6Start.yearGMT(),month6Start.monthGMT(),noOfDays);
        
        if(Date.today() > dueDate){
            dueDate = dueDate.addMonths(6);
            noOfDays = Date.daysInMonth(dueDate.year(),dueDate.month());
            dueDate = Date.newInstance(dueDate.year(),dueDate.month(),noOfDays);
        }
                
        certiRating = [SELECT Id, X0LevelHigh__c, X0LevelLow__c,X1LevelHigh__c,X1LevelLow__c,X2LevelHigh__c,X2LevelLow__c,
                         X3LevelHigh__c,X3LevelLow__c,X4LevelHigh__c,X4LevelLow__c,Deactivated__c,Roles_enabled__c,Numeric_Weight__c,
                         Field_Name__c,name,User_Type__c  FROM Certification_Rating__c where Assessment_type__c='Qualitative' 
                         AND Deactivated__c = false And Timing__c='Bi-annual'];        
            
        if(certiRating != null && certiRating.size() > 0 ){
            
              for(Certification__c s: certs){
                                    
                  for(Certification_Rating__c cr : certiRating){                  
                      
                      Set<String> rolesSet = new Set<String>();
                    
                      if(cr.Roles_enabled__c != null){
                            List<String> rolesList = cr.Roles_enabled__c.split(';');
                            for(String r:rolesList){
                                rolesSet.add(r);
                            }
                      }
                                            
                      if(cr.Roles_enabled__c != null  && (s.Sales_Rep_Profile__r.Rep_Staus__c == cr.User_Type__c  || cr.User_Type__c =='Both') && s.Sales_Rep_Profile__r.Role__c != null && rolesSet.contains(s.Sales_Rep_Profile__r.Role__c)){                      
                      
                          system.debug(' condition matched ');
                          
                          Certification_Answer__c ca= new Certification_Answer__c();
                          ca.Name = cr.name;
                          ca.Certifcation__c = s.id;
                          ca.Certifcation_Rating__c = cr.id;
                          ca.Sales_Rep_Profile__c=s.Sales_Rep_Profile__c;                                                    

                          ca.Due_Date__c = dueDate;
                          ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-7);
                          
                          if(ns.Enable_Notifications__c ){
                          
                                if(ns.Advance_Reminders__c == '1 day prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-1);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-1);
                                }
                                else if(ns.Advance_Reminders__c == '3 days prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-3);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-3);
                                }
                                else if(ns.Advance_Reminders__c == '7 days prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-7);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-7);
                                }
                                
                                if(ns.Escalation__c == '2 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 2;
                                }
                                else if(ns.Escalation__c == '7 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 7;
                                }
                                else if(ns.Escalation__c == '10 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 10;
                                }
                          }
                    
                          createAnsRecords.add(ca);                                          
                          
                      }
                                                                
                  }
                                    
              }
                            
        }
        
        //Creating certification answers for annual ratings
        
        Fyear = FunnelTriggerBatchHelper.getFiscalYearDate('Current_Year');
        DateTime month12Start = Fyear.addMonths(11);
        
        noOfDays = Date.daysInMonth(month12Start.yearGMT(),month12Start.monthGMT());
        
        dueDate = Date.newInstance(month12Start.yearGMT(),month12Start.monthGMT(),noOfDays);
                
        certiRating = [SELECT Id, X0LevelHigh__c, X0LevelLow__c,X1LevelHigh__c,X1LevelLow__c,X2LevelHigh__c,X2LevelLow__c,
                         X3LevelHigh__c,X3LevelLow__c,X4LevelHigh__c,X4LevelLow__c,Deactivated__c,Roles_enabled__c,Numeric_Weight__c,
                         Field_Name__c,name,User_Type__c  FROM Certification_Rating__c where Assessment_type__c='Qualitative' 
                         AND Deactivated__c = false And Timing__c='Annual'];        
            
        if(certiRating != null && certiRating.size() > 0 ){
            
              for(Certification__c s: certs){
                                    
                  for(Certification_Rating__c cr : certiRating){                  
                      
                      Set<String> rolesSet = new Set<String>();
                    
                      if(cr.Roles_enabled__c != null){
                            List<String> rolesList = cr.Roles_enabled__c.split(';');
                            for(String r:rolesList){
                                rolesSet.add(r);
                            }
                      }
                                            
                      if(cr.Roles_enabled__c != null  && (s.Sales_Rep_Profile__r.Rep_Staus__c == cr.User_Type__c  || cr.User_Type__c =='Both') && s.Sales_Rep_Profile__r.Role__c != null && rolesSet.contains(s.Sales_Rep_Profile__r.Role__c)){                      
                          
                          system.debug(' condition matched ');
                          
                          Certification_Answer__c ca= new Certification_Answer__c();
                          ca.Name = cr.name;
                          ca.Certifcation__c = s.id;
                          ca.Certifcation_Rating__c = cr.id;
                          ca.Sales_Rep_Profile__c=s.Sales_Rep_Profile__c;                                                    

                          ca.Due_Date__c = dueDate;
                          ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-7);
                          
                          if(ns.Enable_Notifications__c ){
                          
                                if(ns.Advance_Reminders__c == '1 day prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-1);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-1);
                                }
                                else if(ns.Advance_Reminders__c == '3 days prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-3);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-3);
                                }
                                else if(ns.Advance_Reminders__c == '7 days prior'){
                                    ca.Manager_Email_Date__c = ca.Due_Date__c.addDays(-7);
                                    ca.Rating_Start_Date__c = ca.Due_Date__c.addDays(-7);
                                }
                                
                                if(ns.Escalation__c == '2 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 2;
                                }
                                else if(ns.Escalation__c == '7 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 7;
                                }
                                else if(ns.Escalation__c == '10 days overdue'){
                                    ca.Escalation_Email_Date__c = ca.Due_Date__c + 10;
                                }
                          }
                    
                          createAnsRecords.add(ca);                                          
                          
                      }
                                                                
                  }
                                    
              }
                            
        }
        
        certs[0].Total_Quantitative_Weight__c = createAnsRecords.size();
        update certs[0];
        system.debug(' ans records created '+createAnsRecords);
        insert createAnsRecords;
    }
    
    public static void createCerts(Set<Id> createCertList){
        
        List<Certification__c> certs = [SELECT id, Sales_Rep_Profile__c FROM Certification__c WHERE Sales_Rep_Profile__c IN :createCertList AND Sales_rep_profile__r.Active__c = TRUE];
        
        List<Sales_Rep_Profile__c> sreps = [SELECT id, name FROM Sales_Rep_Profile__c WHERE id IN :createCertList AND Active__c = TRUE];
        
        Map<id,Sales_Rep_Profile__c> srMap = new Map<id,Sales_Rep_Profile__c> ();
        
        for(Sales_Rep_Profile__c s: sreps){
            srMap.put(s.id,s);    
        }
        
        for(Certification__c c: certs){
            if(createCertList != null && createCertList.contains(c.Sales_Rep_Profile__c)){
                createCertList.remove(c.Sales_Rep_Profile__c);
            }    
        } 
        
        List<Certification__c> certsLi = new List<Certification__c>();
        
        for(Id i : createCertList){
            Certification__c c = new Certification__c();
            c.name = srMap.get(i).name + ' Cert';
            c.Sales_Rep_Profile__c = i;
            certsLi.add(c);
        }
        
        insert certsLi;      
    }    
}