funnelocity/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Days_for_closure__c</fullName>
        <description>The number of days taken to successfully close the opportunity (Stage  = Closed Won)</description>
        <formula>if( CloseDate &gt;= DATEVALUE(CreatedDate), (CloseDate - DATEVALUE(CreatedDate)),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days for closure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sales representative to which the opportunity is assigned</description>
        <label>Sales Rep Profile</label>
        <referenceTo>Sales_Rep_Profile__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

funnelocity/src/objects/Sales_Rep_Profile__c.object
<CustomObject>
    <description>Object used to store the details of every person in the sales team</description>
    <fields>
        <fullName>Annual_Quota_Amount__c</fullName>
        <description>Total quota for a year (sum of quotas for every month)</description>
        <formula>Month_1_Quota_Amount__c+Month_2_Quota_Amount__c+Month_3_Quota_Amount__c+Month_4_Quota_Amount__c+Month_5_Quota_Amount__c+Month_6_Quota_Amount__c+Month_7_Quota_Amount__c+Month_8_Quota_Amount__c+Month_9_Quota_Amount__c+Month_10_Quota_Amount__c+Month_11_Quota_Amount__c+Month_12_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Quota Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X12_Month_Opprties_Added_to_the_funnel__c</fullName>
        <description>Number of opportunities added to the sales profile for the past 12 months</description>
        <label>12 Month Opprties Added to the funnel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X12_Month_Rolling_Average_Sales_Cycle__c</fullName>
        <description># of days between becoming an opp and close/won for the past 12 months</description>
        <label>12 Month Rolling Average Sales Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X12_Month_Rolling_Opptys_Won__c</fullName>
        <description>Count of Opportunities marked Closed/Won in the past 12 months</description>
        <label>12 Month Rolling Opptys Won</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X12_Month_Rolling_Quota__c</fullName>
        <description>Stores the sum of quota for the last 12 months</description>
        <label>12 Month Rolling Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X12_Month_Rolling_Revenue__c</fullName>
        <description>Sum of revenue for past 12 months</description>
        <label>12 Month Rolling Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

funnelocity/src/objects/YTD_Quota_Revenue__c.object
<CustomObject>
    <description>The object stores the data that is re-calculated for every fiscal year</description>
    <fields>
        <fullName>Annual_Quota_Amount__c</fullName>
        <description>Stores the sum of quotas for all 12 months</description>
        <formula>Month_1_Quota_Amount__c+Month_2_Quota_Amount__c+Month_3_Quota_Amount__c+Month_4_Quota_Amount__c+Month_5_Quota_Amount__c+Month_6_Quota_Amount__c+Month_7_Quota_Amount__c+Month_8_Quota_Amount__c+Month_9_Quota_Amount__c+Month_10_Quota_Amount__c+Month_11_Quota_Amount__c+Month_12_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Quota Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the sales rep profile to which the quota/revenue record is associated</description>
        <label>Sales Rep Profile</label>
        <referenceTo>Sales_Rep_Profile__c</referenceTo>
        <relationshipLabel>YTD Quota/Revenues</relationshipLabel>
        <relationshipName>YTD_Quota_Revenues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <description>Stores the start date of the fiscal year</description>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <label>YTD Quota/Revenue</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>YTD Quota/Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>YTD Quota/Revenues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/YTD_Quota_Revenue__c/fields/X12_Month_Opprties_Added_to_the_funnel__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Opprties_Added_to_the_funnel__c</fullName>
    <label>12 Month Opprties Added to the funnel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/YTD_Quota_Revenue__c/fields/X12_Month_Rolling_Average_Sales_Cycle__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Rolling_Average_Sales_Cycle__c</fullName>
    <label>12 Month Rolling Average Sales Cycle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

funnelocity/src/classes/Funnel12MonthRollingFieldsBatch.cls
public class Funnel12MonthRollingFieldsBatch implements Database.Batchable<sobject>{

    public Database.QueryLocator start(Database.BatchableContext con){
         return Database.getQueryLocator('select id, Annual_Quota_Amount__c, (select id,amount,StageName,Days_for_closure__c  from Opportunities__r where CreatedDate = LAST_N_days:365 ) from Sales_Rep_Profile__c');
    }
    
    public void execute(Database.BatchableContext con, List<Sales_Rep_Profile__c> srp){
        //list<Sales_Rep_Profile__c> updatesrp = new list<Sales_Rep_Profile__c>();
        
        //List of sales rep ids that are being processed
        Set<Id> srIds = fetchSalesRepIds(srp);
        
        //Fetch the previous fiscal year start date to fetch the data stored for last year
        Date fiscalYr = FunnelTriggerHelper.getFiscalYearDate('Current_Year');        
        Date prevYr = Date.newInstance((fiscalYr.year() - 1), fiscalYr.month(), fiscalYr.day());
        
        //Find the months to be considered in the previous and current fiscal years for calculation of 12 month rolling quota
        Integer currentFiscalMonths, previousFiscalMonths = 0;               
        fetchMonthsForCalculation(currentFiscalMonths, previousFiscalMonths);
        
        //Fetch the quota for the previous year
        Map<Id,Integer> spQuotaMap = fetchQuotaForPastYr(prevYr ,srIds);
                                
        for(Sales_Rep_Profile__c s : srp){
            
            integer countWon = 0,countTotal = 0,avg = 0, countCycle = 0;
            Decimal a = 0;
                        
            for(opportunity o : s.Opportunities__r){
                if(o.StageName == 'Closed Won'){
                    countWon++;
                    if(o.amount != null){
                    a+=o.amount;
                    }
                    countCycle = (integer)(countCycle + o.Days_for_closure__c);
                }
                countTotal++;
                
            }
            if(countCycle != 0 && countWon!= 0 ){
                avg = countCycle/countWon;
            } else{
                avg =0;
            }
            
            s.X12_Month_Rolling_Opptys_Won__c = countWon;
            s.X12_Month_Rolling_Revenue__c = a;
            s.X12_Month_Opprties_Added_to_the_funnel__c = countTotal;
            s.X12_Month_Rolling_Average_Sales_Cycle__c = avg;            
            s.X12_Month_Rolling_Quota__c = ((s.Annual_Quota_Amount__c/12) * currentFiscalMonths); 
            
            if(spQuotaMap.get(s.id) != null){                
                s.X12_Month_Rolling_Quota__c = s.X12_Month_Rolling_Quota__c + (spQuotaMap.get(s.id) * previousFiscalMonths);
            }
            system.debug('countTotal'+countTotal);
        }
        
        update srp;
        //system.debug(srp);
    }
    
    public void finish(Database.BatchableContext con){
    
    }
    
    private void fetchMonthsForCalculation(Integer currentFiscalMonths, Integer previousFiscalMonths){
        
        Integer startMonth = FunnelTriggerHelper.getFiscalYearDate('Current_Year').Month();
        Integer currentMonth = Date.Today().Month();
        
        if(currentMonth > startMonth){
            currentFiscalMonths = currentMonth - startMonth;            
        }
        else if(currentMonth < startMonth){
            currentFiscalMonths = 12 - startMonth + currentMonth;            
        }
        else if(currentMonth == startMonth){
            currentFiscalMonths = 1;
        }
        
        previousFiscalMonths = 12 - currentFiscalMonths;
                
    }
    
    private Map<Id,Integer> fetchQuotaForPastYr(Date startDate, Set<Id> salesReps){
        
        Map<Id,Integer> spQuotaMap = new Map<Id,Integer>();

        List<YTD_Quota_Revenue__c> previousYearData = [SELECT Id, Annual_Quota_Amount__c FROM YTD_Quota_Revenue__c WHERE Start_date__c = :startDate AND Sales_Rep_Profile__c IN :salesReps];                
        
        for(YTD_Quota_Revenue__c qr: previousYearData){
        
            spQuotaMap.put(qr.Sales_Rep_Profile__c , (Integer)qr.Annual_Quota_Amount__c/12);    
        }
        
        return spQuotaMap;
    }
    
    private Set<Id> fetchSalesRepIds(List<Sales_Rep_Profile__c> salesReps){
    
        Set<Id> salesRepIds = new Set<Id>();
        
        for(Sales_Rep_Profile__c sr: salesReps){
            salesRepIds.add(sr.id);
        }
        
        return salesRepIds;
    }
}