funnelocity/src/objects/Sales_Rep_Profile__c.object
<CustomObject>
    <description>Object used to store the details of every person in the sales team</description>
    <fields>
        <fullName>Annual_Quota_Amount__c</fullName>
        <description>Total quota for a year (sum of quotas for every month)</description>
        <formula>Month_1_Quota_Amount__c+Month_2_Quota_Amount__c+Month_3_Quota_Amount__c+Month_4_Quota_Amount__c+Month_5_Quota_Amount__c+Month_6_Quota_Amount__c+Month_7_Quota_Amount__c+Month_8_Quota_Amount__c+Month_9_Quota_Amount__c+Month_10_Quota_Amount__c+Month_11_Quota_Amount__c+Month_12_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Quota Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_10_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 10</description>
        <label>Month 10 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_11_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 11</description>
        <label>Month 11 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_12_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 12</description>
        <label>Month 12 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_1_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 1</description>
        <label>Month 1 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_2_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 2</description>
        <label>Month 2 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_3_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 3</description>
        <label>Month 3 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_4_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 4</description>
        <label>Month 4 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_5_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 5</description>
        <label>Month 5 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_6_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 6</description>
        <label>Month 6 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_7_Quota_Amount__c</fullName>
        <label>Month 7 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_8_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 8</description>
        <label>Month 8 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_9_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 9</description>
        <label>Month 9 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q1_Quota_Amount__c</fullName>
        <description>Month 1 quota + Month 2 quota + Month 3 quota</description>
        <formula>Month_1_Quota_Amount__c + Month_2_Quota_Amount__c + Month_3_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q1 Quota Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q2_Quota_Amount__c</fullName>
        <description>Month 4 quota + Month 5 quota + Month 6 quota</description>
        <formula>Month_4_Quota_Amount__c + Month_5_Quota_Amount__c + Month_6_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q2 Quota Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q3_Quota_Amount__c</fullName>
        <description>Month 7 quota + Month 8 quota + Month 9 quota</description>
        <formula>Month_7_Quota_Amount__c + Month_8_Quota_Amount__c + Month_9_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q3 Quota Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Q4_Quota_Amount__c</fullName>
        <description>Month 10 quota + Month 11 quota + Month 12 quota</description>
        <formula>Month_10_Quota_Amount__c + Month_11_Quota_Amount__c + Month_12_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Q4 Quota Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YTD_Average_Sales_Cycle__c</fullName>
        <description>Average number of days taken to close an opportunity YTD (Configured as fiscal/calendar year during app setup)</description>
        <label>YTD Average Sales Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YTD_Opportunities_won__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of opportunities won by the sales rep in the calendar/fiscal year (configured during the app setup)</description>
        <label>YTD Opportunities Won</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YTD_Revenue_Close_Rate__c</fullName>
        <description>Percentage of Revenue closed versus annual quota</description>
        <formula>YTD_Revenue__c / Annual_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YTD Revenue Close Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YTD_Revenue_Quota_Percent__c</fullName>
        <formula>YTD_Revenue__c / Annual_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YTD Revenue Quota Percent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YTD_Revenue__c</fullName>
        <description>Sum of Revenue from won opportunities YTD (calendar/fiscal year configured during the app setup is considered) for sales rep</description>
        <label>YTD Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YTD_Win_Percentage__c</fullName>
        <formula>YTD_Opportunities_won__c / Current_Active_Opportunities__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YTD Win Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

funnelocity/src/objects/YTD_Quota_Revenue__c.object
<CustomObject>
    <description>The object stores the data that is re-calculated for every fiscal year</description>
    <fields>
        <fullName>Annual_Quota_Amount__c</fullName>
        <description>Stores the sum of quotas for all 12 months</description>
        <formula>Month_1_Quota_Amount__c+Month_2_Quota_Amount__c+Month_3_Quota_Amount__c+Month_4_Quota_Amount__c+Month_5_Quota_Amount__c+Month_6_Quota_Amount__c+Month_7_Quota_Amount__c+Month_8_Quota_Amount__c+Month_9_Quota_Amount__c+Month_10_Quota_Amount__c+Month_11_Quota_Amount__c+Month_12_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Quota Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_10_Quota_Amount__c</fullName>
        <description>Field to store the quota for the tenth month of the fiscal year</description>
        <label>Month 10 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_11_Quota_Amount__c</fullName>
        <description>Field to store the quota for the eleventh month of the fiscal year</description>
        <label>Month 11 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_12_Quota_Amount__c</fullName>
        <description>Field to store the quota for the twelfth month of the fiscal year</description>
        <label>Month 12 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_1_Quota_Amount__c</fullName>
        <description>Stores the quota amount for the first month of the fiscal year</description>
        <label>Month 1 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_2_Quota_Amount__c</fullName>
        <description>Field to store the quota for the second month of the fiscal year</description>
        <label>Month 2 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_3_Quota_Amount__c</fullName>
        <description>Field to store the quota for the third month of the fiscal year</description>
        <label>Month 3 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_4_Quota_Amount__c</fullName>
        <description>Field to store the quota for the fourth month of the fiscal year</description>
        <label>Month 4 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_5_Quota_Amount__c</fullName>
        <description>Field to store the quota for the fifth month of the fiscal year</description>
        <label>Month 5 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_6_Quota_Amount__c</fullName>
        <description>Field to store the quota for the sixth month of the fiscal year</description>
        <label>Month 6 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_7_Quota_Amount__c</fullName>
        <description>Field to store the quota for the seventh month of the fiscal year</description>
        <label>Month 7 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_8_Quota_Amount__c</fullName>
        <description>Field to store the quota for the eighth month of the fiscal year</description>
        <label>Month 8 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_9_Quota_Amount__c</fullName>
        <label>Month 9 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YTD_Opportunities_Won__c</fullName>
        <description>Number of opportunities won by the sales rep in the calendar/fiscal year</description>
        <label>YTD Opportunities Won</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YTD_Revenue__c</fullName>
        <description>Sum of Revenue from won opportunities in the current fiscal year</description>
        <label>YTD Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>YTD Quota/Revenue</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>YTD Quota/Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>YTD Quota/Revenues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/YTD_Quota_Revenue__c/fields/YTD_Average_Sales_Cycle__c.field-meta.xml
<CustomField>
    <fullName>YTD_Average_Sales_Cycle__c</fullName>
    <description>Stores the average sales cycle for the year</description>
    <label>YTD Average Sales Cycle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/YTD_Quota_Revenue__c/fields/YTD_Revenue_Close_Rate__c.field-meta.xml
<CustomField>
    <fullName>YTD_Revenue_Close_Rate__c</fullName>
    <description>Revenue close rate copied from the sales profile object</description>
    <label>YTD Revenue Close Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/YTD_Quota_Revenue__c/fields/YTD_Revenue_Quota_Percent__c.field-meta.xml
<CustomField>
    <fullName>YTD_Revenue_Quota_Percent__c</fullName>
    <description>Revenue quota percent copied from the sales profile object</description>
    <label>YTD Revenue Quota Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/YTD_Quota_Revenue__c/fields/YTD_Win_Percentage__c.field-meta.xml
<CustomField>
    <fullName>YTD_Win_Percentage__c</fullName>
    <description>Win percentage copied from the sales profile object</description>
    <label>YTD Win Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

funnelocity/src/classes/FunnelYearlyBatch.cls
public class FunnelYearlyBatch implements Database.Batchable<sobject>{
    
    public Date fiscalYr;
    
    public Date nextYr;
    
    public Database.QueryLocator start(Database.BatchableContext con){
         return Database.getQueryLocator('Id, YTD_Opportunities_won__c, YTD_Revenue__c, YTD_Revenue_Quota_Percent__c, YTD_Win_Percentage__c, YTD_Average_Sales_Cycle__c, YTD_Revenue_Close_Rate__c, Month_1_Quota_Amount__c, Month_2_Quota_Amount__c, Month_3_Quota_Amount__c, Month_4_Quota_Amount__c, Month_5_Quota_Amount__c, Month_6_Quota_Amount__c, Month_7_Quota_Amount__c, Month_9_Quota_Amount__c, Month_8_Quota_Amount__c, Month_10_Quota_Amount__c, Month_11_Quota_Amount__c, Month_12_Quota_Amount__c, Annual_Quota_Amount__c, Q1_Quota_Amount__c, Q2_Quota_Amount__c, Q3_Quota_Amount__c, Q4_Quota_Amount__c, Sales_Manager__c, Aggregated_Annual_Quota__c FROM Sales_Rep_Profile__c');
    }
    
    public void execute(Database.BatchableContext con, List<Sales_Rep_Profile__c> srp){
        
        //Fetch the previous fiscal year start date to fetch the data stored for last year
        fiscalYr = FunnelTriggerBatchHelper.getFiscalYearDate('Current_Year');        
        nextYr = Date.newInstance((fiscalYr.year() + 1), fiscalYr.month(), fiscalYr.day());                
        
        List<YTD_Quota_Revenue__c> quotaRecsToBeInserted = new List<YTD_Quota_Revenue__c>();   
                             
        for(Sales_Rep_Profile__c s : srp){
        
            YTD_Quota_Revenue__c yq = new YTD_Quota_Revenue__c();
            yq.Month_1_Quota_Amount__c = s.Month_1_Quota_Amount__c;
            yq.Month_2_Quota_Amount__c = s.Month_2_Quota_Amount__c;
            yq.Month_3_Quota_Amount__c = s.Month_3_Quota_Amount__c;
            yq.Month_4_Quota_Amount__c = s.Month_4_Quota_Amount__c;
            yq.Month_5_Quota_Amount__c = s.Month_5_Quota_Amount__c;
            yq.Month_6_Quota_Amount__c = s.Month_6_Quota_Amount__c;
            yq.Month_7_Quota_Amount__c = s.Month_7_Quota_Amount__c;
            yq.Month_8_Quota_Amount__c = s.Month_8_Quota_Amount__c;
            yq.Month_9_Quota_Amount__c = s.Month_9_Quota_Amount__c;
            yq.Month_10_Quota_Amount__c = s.Month_10_Quota_Amount__c;
            yq.Month_11_Quota_Amount__c = s.Month_11_Quota_Amount__c;
            yq.Month_12_Quota_Amount__c = s.Month_12_Quota_Amount__c;
            yq.Sales_Rep_Profile__c = s.id;
            yq.Start_date__c = fiscalYr;
            yq.YTD_Opportunities_Won__c = s.YTD_Opportunities_won__c;
            yq.YTD_Revenue__c = s.YTD_Revenue__c;
            quotaRecsToBeInserted.add(yq);  
            
            s.Month_1_Quota_Amount__c = 0;
            s.Month_2_Quota_Amount__c = 0;
            s.Month_3_Quota_Amount__c = 0;
            s.Month_4_Quota_Amount__c = 0;
            s.Month_5_Quota_Amount__c = 0;
            s.Month_6_Quota_Amount__c = 0;
            s.Month_7_Quota_Amount__c = 0;
            s.Month_8_Quota_Amount__c = 0;
            s.Month_9_Quota_Amount__c = 0;
            s.Month_10_Quota_Amount__c = 0;
            s.Month_11_Quota_Amount__c = 0;
            s.Month_12_Quota_Amount__c = 0;
            s.YTD_Opportunities_won__c = 0;
            s.YTD_Revenue__c = 0;                      
        }
        
        insert quotaRecsToBeInserted;
        update srp;
        //system.debug(srp);
        
    }
    
    public void finish(Database.BatchableContext con){
        
        Fiscal_Year_Setting__c fy = FunnelTriggerBatchHelper.getFiscalYearRecord('Current_Year');
        fy.Start_Date__c = nextYr;
        update fy;
                        
    }
}