funnelocity/src/objects/Sales_Rep_Profile__c.object
<CustomObject>
    <description>Object used to store the details of every person in the sales team</description>
    <fields>
        <fullName>Annual_Opportunity_Quota__c</fullName>
        <formula>Annual_Win_Quota__c / YTD_Win_Percentage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Opportunity Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Quota_Amount__c</fullName>
        <description>Total quota for a year (sum of quotas for every month)</description>
        <formula>Month_1_Quota_Amount__c+Month_2_Quota_Amount__c+Month_3_Quota_Amount__c+Month_4_Quota_Amount__c+Month_5_Quota_Amount__c+Month_6_Quota_Amount__c+Month_7_Quota_Amount__c+Month_8_Quota_Amount__c+Month_9_Quota_Amount__c+Month_10_Quota_Amount__c+Month_11_Quota_Amount__c+Month_12_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Quota Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annual_Win_Quota__c</fullName>
        <formula>Annual_Quota_Amount__c / Average_Sales_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Win Quota</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Average_Sales_Price__c</fullName>
        <formula>YTD_Revenue__c / YTD_Opportunities_won__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Sales Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Active_Opportunities__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total number of opportunities assigned to a sales representative that are in the active stage</description>
        <label>Current Active Opportunities</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Opportunity_Quota__c</fullName>
        <formula>Annual_Opportunity_Quota__c / 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monthly Opportunity Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Wins__c</fullName>
        <formula>Annual_Win_Quota__c / 12</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Monthly Wins</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarterly_Opportunity_Quota__c</fullName>
        <formula>Annual_Opportunity_Quota__c / 4</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quarterly Opportunity Quota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quarterly_Wins__c</fullName>
        <formula>Annual_Win_Quota__c / 4</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quarterly Wins</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X12_Month_Opprties_Added_to_the_funnel__c</fullName>
        <description>Number of opportunities added to the sales profile for the past 12 months</description>
        <label>12 Month Opprties Added to the funnel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X12_Month_Rolling_Average_Sales_Cycle__c</fullName>
        <description># of days between becoming an opp and close/won for the past 12 months</description>
        <label>12 Month Rolling Average Sales Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X12_Month_Rolling_Opptys_Won__c</fullName>
        <description>Count of Opportunities marked Closed/Won in the past 12 months</description>
        <label>12 Month Rolling Opptys Won</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X12_Month_Rolling_Revenue__c</fullName>
        <description>Sum of revenue for past 12 months</description>
        <label>12 Month Rolling Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X12_Month_Rolling_Win_Percentage__c</fullName>
        <description># of won opps / # of opps for the past 12 months</description>
        <formula>X12_Month_Rolling_Opptys_Won__c / X12_Month_Opprties_Added_to_the_funnel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>12 Month Rolling Win Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YTD_Average_Sales_Cycle__c</fullName>
        <description>Average number of days taken to close an opportunity YTD (Configured as fiscal/calendar year during app setup)</description>
        <label>YTD Average Sales Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YTD_Opportunities_won__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of opportunities won by the sales rep in the calendar/fiscal year (configured during the app setup)</description>
        <label>YTD Opportunities Won</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YTD_Revenue_Close_Rate__c</fullName>
        <description>Percentage of Revenue closed versus annual quota</description>
        <formula>YTD_Revenue__c / Annual_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YTD Revenue Close Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YTD_Revenue_Quota_Percent__c</fullName>
        <formula>YTD_Revenue__c / Annual_Quota_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YTD Revenue Quota Percent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YTD_Revenue__c</fullName>
        <description>Sum of Revenue from won opportunities YTD (calendar/fiscal year configured during the app setup is considered) for sales rep</description>
        <label>YTD Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YTD_Win_Percentage__c</fullName>
        <formula>YTD_Opportunities_won__c / Current_Active_Opportunities__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>YTD Win Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

funnelocity/src/classes/SalesProfile.cls
public class SalesProfile {
    @AuraEnabled
    public static Sales_Rep_Profile__c getsaleprof(Id accountId){
        return [select id,X12_Month_Opprties_Added_to_the_funnel__c,
                X12_Month_Rolling_Average_Sales_Cycle__c,X12_Month_Rolling_Opptys_Won__c,
				X12_Month_Rolling_Revenue__c,X12_Month_Rolling_Win_Percentage__c,
				Annual_Opportunity_Quota__c,Annual_Quota_Amount__c,Annual_Win_Quota__c,
				Average_Sales_Price__c,Current_Active_Opportunities__c,Monthly_Wins__c,
				Quarterly_Opportunity_Quota__c,Quarterly_Wins__c,YTD_Average_Sales_Cycle__c,
				YTD_Opportunities_won__c,YTD_Revenue__c,YTD_Revenue_Close_Rate__c,
				YTD_Revenue_Quota_Percent__c,YTD_Win_Percentage__c,Monthly_Opportunity_Quota__c
				from Sales_Rep_Profile__c where Id=:accountId];
    }

}