funnelocity/src/objects/Sales_Rep_Profile__c.object
<CustomObject>
    <description>Object used to store the details of every person in the sales team</description>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the user record associated with the sales profile is active</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/Sales_Rep_Profile_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Store Sales Rep Profile Snapshot</description>
    <label>Sales Rep Profile Snapshot</label>
    <nameField>
        <label>Sales Rep Profile Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profile Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the sales profile for which the snapshot was taken was active</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/Sales_Rep_Profile__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep Profile</label>
    <referenceTo>Sales_Rep_Profile__c</referenceTo>
    <relationshipLabel>Sales Rep Profile Snapshots (Sales Rep Profile)</relationshipLabel>
    <relationshipName>Sales_Rep_Profile_Snapshots1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FunnelPushQuantData.cls
global with sharing class FunnelPushQuantData implements Database.Batchable<sobject>, Database.Stateful, Database.AllowsCallouts{
    
    Date snapDate;
    
    Boolean errorVal = false;
    
    public FunnelPushQuantData(){
        
        List<Sales_Rep_Profile_Snapshot__c> snapshotRecsToBeInserted = new List<Sales_Rep_Profile_Snapshot__c>();   
            
        List<Sales_rep_profile_snapshot__c> snaps = new List<Sales_rep_profile_snapshot__c>();
        
        snaps = [SELECT Snapshot_scheduled_date__c FROM Sales_rep_profile_snapshot__c ORDER BY Snapshot_scheduled_date__c DESC LIMIT 1];
        
        if(snaps != null && snaps.size()>0){
            snapDate = snaps[0].Snapshot_scheduled_date__c;   
        }
         
    }
    
    public static String prefix{ get{return '';} set; }

    public Database.QueryLocator start(Database.BatchableContext con){                
        
        return Database.getQueryLocator('SELECT Id FROM Sales_Rep_Profile__c WHERE Active__c = TRUE LIMIT 5000');
    }
    
    public void execute(Database.BatchableContext con, List<Sales_Rep_Profile__c> srp){
        try{    
            
            if(snapDate != null){
              
                FunnelPostAPIs fp = new FunnelPostAPIs();
                fp.getAccessToken();        
                fp.dtSnapShot = snapDate;
                fp.createQuantMetric(srp);
                system.debug(' fp.msg '+fp.msg);
              
            }      
                              
        }
        catch(Exception ex){
            errorVal = true;
            FunnelTriggerBatchHelper.sendErrorMail(' FunnelPushQuantData '+ex.getMessage()+' '+ex.getStackTraceString()+ ' line number: '+ex.getLineNumber()+' cause '+ex.getCause());
            system.debug(' error has occured '+ex.getMessage());
        }
           
    }
    
    public void finish(Database.BatchableContext con){
                                         
    }
}