force-app/main/default/objects/Application_Setting__c/Application_Setting__c.object-meta.xml
<CustomObject>
    <description>This object stores the App setup information.</description>
    <label>Application Setting</label>
    <nameField>
        <label>Application Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Setting__c/fields/Probability__c.field-meta.xml
<CustomField>
    <fullName>Probability__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Stores the user Qualified probability value.</description>
    <label>Probability</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

funnelocity/src/objects/Fiscal_Year_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store the current fiscal year start date</description>
    <label>Fiscal Year Setting</label>
</CustomObject>

funnelocity/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The sales representative to which the opportunity is assigned</description>
        <label>Sales Rep Profile</label>
        <referenceTo>Sales_Rep_Profile__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

funnelocity/src/objects/Sales_Rep_Profile__c.object
<CustomObject>
    <description>Object used to store the details of every person in the sales team</description>
    <fields>
        <fullName>Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the manager of the sales representative</description>
        <label>Sales Manager</label>
        <referenceTo>Sales_Rep_Profile__c</referenceTo>
        <relationshipLabel>Sales Rep Profiles</relationshipLabel>
        <relationshipName>Sales_Rep_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/Monthly_QO_added__c.field-meta.xml
<CustomField>
    <fullName>Monthly_QO_added__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This field is counter for monthly QO added</description>
    <label>Monthly QO added</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FunnelTriggerBatchHelperTest.cls
@isTest

public class FunnelTriggerBatchHelperTest{

    static testmethod void testOpptyCounter(){

        FunnelDataFactory.FunnelTestWrapper fw1 = new FunnelDataFactory.FunnelTestWrapper();
        
        fw1.index = 1;   
        fw1.ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
        
        
        UserRole r1 = new UserRole(DeveloperName = 'MyCustomRole0A'+fw1.index , Name = 'My Role'+fw1.index);
        insert r1;
        
        fw1.userRoleId = r1.id;
        
        List<User> userList1 = FunnelDataFactory.createUser(fw1,1);
        insert userList1;                
            
        //PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'Funnel_Sales_Profile_Company_Level_access'];
        //insert new PermissionSetAssignment(AssigneeId = userList1[0].id, PermissionSetId = ps.Id );
        
        System.runAs ( userList1[0] ) {
        
            date d = date.newinstance(date.today().year(), 1, 1);
            Fiscal_Year_Setting__c fiscalYr = FunnelDataFactory.setFiscalYear(d);
            insert fiscalYr;
            
            Application_Setting__c appSet = new Application_Setting__c(Probability__c=20);
            insert appSet;
        
            FunnelDataFactory.FunnelTestWrapper fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.index = 1;   
            fw.ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
                    
            UserRole r = new UserRole(DeveloperName = 'MyCustomRole'+fw.index , Name = 'My Role'+fw.index);
            insert r;
            
            fw.userRoleId = r.id;
            
            List<User> userList = FunnelDataFactory.createUser(fw,2);
            insert userList;
            system.debug(userList);
            
            List<Sales_Rep_Profile__c> sp = FunnelDataFactory.createSalesReplist(userList);
            insert sp;            
            
            sp[0].Sales_Manager__c = sp[1].id;
            update sp[0];                       
            
            List<Opportunity > op= FunnelDataFactory.createopplist(userList);
            op[0].Probability = 10;
            op[0].CloseDate = Date.today()+1;
            insert op;           
            
            Test.startTest();
            
            op[0].Probability = 30;
            op[0].CloseDate = Date.today()+40;
            update op;
            
            List<Lead> l= FunnelDataFactory.createLeadlist(userList);
            insert l;
                                                
            Sales_rep_profile__c sr = [SELECT Monthly_QO_Added__c FROM Sales_rep_profile__c WHERE id = :sp[0].id];
            System.assertEquals(1 , sr.Monthly_QO_Added__c);
            
            op[0].StageName = 'Closed/Lost';
            update op;
            
            Test.stopTest();
            
        }
    
    }
          
}