force-app/main/default/objects/Certification_Rating__c/Certification_Rating__c.object-meta.xml
<CustomObject>
    <description>Object used to store the certification question</description>
    <label>Certification Rating</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification_Rating__c/fields/Assessment_type__c.field-meta.xml
<CustomField>
    <fullName>Assessment_type__c</fullName>
    <description>Indicates if the rating is qualitative or quantitative</description>
    <label>Assessment type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualitative</fullName>
            </value>
            <value>
                <fullName>Quantitative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Calculation_type__c.field-meta.xml
<CustomField>
    <fullName>Calculation_type__c</fullName>
    <description>Indicates how the rating is assessed</description>
    <label>Calculation type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y/N</fullName>
            </value>
            <value>
                <fullName>Bucketed</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores the category of the rating</description>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the certification question</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Roles_enabled__c.field-meta.xml
<CustomField>
    <fullName>Roles_enabled__c</fullName>
    <description>Stores the list of sales profile roles for which the certification is active</description>
    <label>Roles enabled</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Timing__c.field-meta.xml
<CustomField>
    <fullName>Timing__c</fullName>
    <defaultValue>&quot;Week&quot;</defaultValue>
    <description>The number of days within which the rating should be completed</description>
    <label>Timing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End of month</fullName>
            </value>
            <value>
                <fullName>End of quarter</fullName>
            </value>
            <value>
                <fullName>Bi-annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Stores if the sales rep is new/tenured</description>
    <label>Assign to onboarded reps?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>Tenured</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Weight assigned to the certification rating</description>
    <label>Weight</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

funnelocity/src/objects/Sales_Rep_Profile__c.object
<CustomObject>
    <description>Object used to store the details of every person in the sales team</description>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Lists the roles in the funnelocity app</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Executive</fullName>
        <label>Account Executive - Hunter</label>
    </customValue>
    <customValue>
        <fullName>Sales Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Operations Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Manager&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>VP</fullName>
    </customValue>
    <customValue>
        <fullName>Continent VP of Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Country VP of Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>SVP of Sales</fullName>
    </customValue>
    <description>Used for the Funnelocity app custom roles</description>
    <masterLabel>Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FunnelAssignRoleControllerTest.cls
@isTest
public class FunnelAssignRoleControllerTest {
    
    static testmethod void testFunnelAssignRoleController() {           
           
            
           test.startTest();
          
           DescribeFieldResult describe = Sales_Rep_Profile__c.Role__c.getDescribe();
           List<PicklistEntry> availableValues = describe.getPicklistValues();
           
           List<Certification_Rating__c> certs = new List<Certification_Rating__c>();
          
            Certification_Rating__c cr = new Certification_Rating__c();
            cr.Assessment_type__c = 'Qualitative';   
            cr.Calculation_type__c = 'Y/N';
            cr.Category__c = 'Test';            
            cr.User_Type__c = 'New';
            cr.Timing__c = 'End of month';
            cr.Weight__c = '4';
            cr.Description__c = 'Test description 1';
            cr.Roles_Enabled__c =  availableValues[0].getValue();
            certs.add(cr);
            
            cr = new Certification_Rating__c();
            cr.Assessment_type__c = 'Qualitative';   
            cr.Calculation_type__c = 'Y/N';
            cr.Category__c = 'Test';            
            cr.User_Type__c = 'New';
            cr.Timing__c = 'End of month';
            cr.Weight__c = '4';
            cr.Description__c = 'Test description 2';
            cr.Roles_Enabled__c =  availableValues[1].getValue();
            certs.add(cr);
         
            cr = new Certification_Rating__c();
            cr.Assessment_type__c = 'Qualitative';   
            cr.Calculation_type__c = 'Y/N';
            cr.Category__c = 'Test';            
            cr.User_Type__c = 'New';
            cr.Timing__c = 'End of month';
            cr.Weight__c = '4';
            cr.Description__c = 'Test description 3';
            certs.add(cr);
            
            insert certs ;
            FunnelAssignRoleController fc = new FunnelAssignRoleController();    
            fc.editCerti();
            fc.updatecerti();
            
            List<Certification_Rating__c> certs1 =[Select id from Certification_Rating__c ];
            system.assertEquals(certs1.size(),3); 
            
            
            test.stopTest();
        
                            
    }
    
    
    
    static testmethod void testNavigation() {           
        
            test.startTest();
            
            FunnelAssignRoleController fc = new FunnelAssignRoleController();                        

            
            PageReference p = fc.navigateToCertification();
            system.assert(true,p.getUrl().contains('FunnelCerificationTable'));
            p = fc.navigateToCalculator();
            system.assert(true,p.getUrl().contains('FunnelCalculator'));
            p = fc.navigateToHomePage();
            system.assert(true,p.getUrl().contains('FunnelHomePage'));
            p = fc.navigateToDashboard();
            system.assert(true,p.getUrl().contains('FunnelSalesDashboard'));
            p = fc.navigateToReportsPage();
            system.assert(true,p.getUrl().contains('FunnelReportingPage'));
            p = fc.navigateToAppSetup();
            system.assert(true,p.getUrl().contains('FunnelSalesCertification'));
            p = fc.navigateToCertificateReports();
            system.assert(true,p.getUrl().contains('FunnelCerificationReports'));
            p = fc.navigateToRatings();
            system.assert(true,p.getUrl().contains('FunnelSalesCertification'));
            p = fc.navigateToNotifications();
            system.assert(true,p.getUrl().contains('FunnelNotification'));
            p = fc.navigateToCategories();
            system.assert(true,p.getUrl().contains('navigateToCategories'));
            p = fc.navigateToAnalytics();
            system.assert(true,p.getUrl().contains('navigateToAnalytics'));
            p = fc.navigateToFunnelAnalyticQualitative();
            system.assert(true,p.getUrl().contains('navigateToFunnelAnalyticQualitative'));
            p = fc.navigateToFunnelAnalytic();
            system.assert(true,p.getUrl().contains('navigateToFunnelAnalytic'));
            
            
            test.stopTest();
         
                            
    }              
    
}