force-app/main/default/objects/Certification_Rating__c/Certification_Rating__c.object-meta.xml
<CustomObject>
    <description>Object used to store the certification question</description>
    <label>Certification Rating</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification_Rating__c/fields/Assessment_type__c.field-meta.xml
<CustomField>
    <fullName>Assessment_type__c</fullName>
    <description>Indicates if the rating is qualitative or quantitative</description>
    <label>Assessment type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualitative</fullName>
            </value>
            <value>
                <fullName>Quantitative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Calculation_type__c.field-meta.xml
<CustomField>
    <fullName>Calculation_type__c</fullName>
    <description>Indicates how the rating is assessed</description>
    <label>Calculation type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y/N</fullName>
            </value>
            <value>
                <fullName>Bucketed</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Stores the category of the rating</description>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Deactivated__c.field-meta.xml
<CustomField>
    <fullName>Deactivated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this rating should not appear for the certifications that are created in future</description>
    <label>Deactivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the certification question</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <description>Stores the order of the rating under a particular category</description>
    <label>Display Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>Store the API name for the Quantitative rating</description>
    <label>Field Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Numeric_Weight__c.field-meta.xml
<CustomField>
    <fullName>Numeric_Weight__c</fullName>
    <description>Store the Numeric Value of picklist</description>
    <formula>VALUE(TEXT( Weight__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Numeric Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Rating_type__c.field-meta.xml
<CustomField>
    <fullName>Rating_type__c</fullName>
    <description>Store the type of rating of quantitative rating</description>
    <label>Rating type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Roles_enabled__c.field-meta.xml
<CustomField>
    <fullName>Roles_enabled__c</fullName>
    <description>Stores the list of sales profile roles for which the certification is active</description>
    <label>Roles enabled</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/SRP_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>SRP_Field_Name__c</fullName>
    <description>Store the destination field on SRP object  (used for custom metrics)</description>
    <label>SRP Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Timing__c.field-meta.xml
<CustomField>
    <fullName>Timing__c</fullName>
    <defaultValue>&quot;Week&quot;</defaultValue>
    <description>The number of days within which the rating should be completed</description>
    <label>Timing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End of month</fullName>
            </value>
            <value>
                <fullName>End of quarter</fullName>
            </value>
            <value>
                <fullName>Bi-annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <description>Stores if the sales rep is new/tenured</description>
    <label>Assign to onboarded reps?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>Tenured</fullName>
                <label>Yes</label>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <description>Weight assigned to the certification rating</description>
    <label>Weight</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X0LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X0LevelHigh__c</fullName>
    <label>0LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X0LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X0LevelLow__c</fullName>
    <label>0LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X1LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X1LevelHigh__c</fullName>
    <label>1LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X1LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X1LevelLow__c</fullName>
    <label>1LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X2LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X2LevelHigh__c</fullName>
    <label>2LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X2LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X2LevelLow__c</fullName>
    <label>2LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X3LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X3LevelHigh__c</fullName>
    <label>3LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X3LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X3LevelLow__c</fullName>
    <label>3LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X4LevelHigh__c.field-meta.xml
<CustomField>
    <fullName>X4LevelHigh__c</fullName>
    <label>4LevelHigh</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Certification_Rating__c/fields/X4LevelLow__c.field-meta.xml
<CustomField>
    <fullName>X4LevelLow__c</fullName>
    <label>4LevelLow</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

funnelocity/src/objects/Sales_Rep_Profile__c.object
<CustomObject>
    <description>Object used to store the details of every person in the sales team</description>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the user record associated with the sales profile is active</description>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Executive</fullName>
        <label>Account Executive - Hunter</label>
    </customValue>
    <customValue>
        <fullName>Sales Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Operations Executive</fullName>
    </customValue>
    <customValue>
        <fullName>Operations Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Manager&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Account Manager</fullName>
    </customValue>
    <customValue>
        <fullName>VP</fullName>
    </customValue>
    <customValue>
        <fullName>Continent VP of Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Country VP of Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Regional Sales Manager</fullName>
    </customValue>
    <customValue>
        <fullName>SVP of Sales</fullName>
    </customValue>
    <description>Used for the Funnelocity app custom roles</description>
    <masterLabel>Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FunnelAssignRoleController.cls
/*
Copyright: Funnel Metrics, LLC
*/
public with sharing class FunnelAssignRoleController{

Public Map<String,String> managemenetReports{get;set;}

public string selectedValue { get;set; }
public list<Certification_Rating__c> certificate {get;set;}
public list<certificateWrapper> cwList{get;set;}
public list<Certification_Rating__c> certificateDisplay {get;set;}
public class certificateWrapper{
    
    public Certification_Rating__c certificateRating{get;set;}
    public Boolean isSelected{ get; set; }
}

public list<certificateWrapper> certificateWrapperList {get;set;} 
public boolean crpanel{get;set;}
public boolean crDisplaypanel{get;set;}
public boolean credit{get;set;}
public static String prefix{ get{return 'FunnelMetrics__';} set; }
public Boolean readAccess = true;
   
    //Variables to store the parameters passed in the URL
    public String label1{get; set;}
    public String label2{get; set;}
    public String label3{get; set;}
    public String selectedLevel1{get; set;}
    public String selectedLevel2{get; set;}
    public String selectedLevel3{get; set;}
    
    public Boolean adminPer{get;set;}
    public Boolean isManger{get;set;}
    /* Filters */    
    
    public FunnelAssignRoleController(){
        try{    
            getRole();   
            selectedValue = defaultRole;
            system.debug('selectedValue ' +selectedValue );
            
            List<String> fldList1 = new List<String>{prefix+'Name', prefix+'Weight__c', prefix+'User_Type__c', prefix+'Timing__c', prefix+'Roles_enabled__c', prefix+'Rating_type__c', prefix+'Numeric_Weight__c', prefix+'Field_Name__c',prefix+'Display_Order__c',prefix+'Description__c',prefix+'Deactivated__c',prefix+'Category__c',prefix+'Calculation_type__c',prefix+'Assessment_type__c',prefix+'X4LevelLow__c',prefix+'X4LevelHigh__c',prefix+'X3LevelLow__c',prefix+'X3LevelHigh__c',prefix+'X2LevelLow__c',prefix+'X2LevelHigh__c',prefix+'X1LevelLow__c',prefix+'X1LevelHigh__c',prefix+'X0LevelLow__c',prefix+'X0LevelHigh__c'};
                
            Map <String, Schema.SObjectField> fieldMap1 = Schema.getGlobalDescribe().get(prefix+'Certification_Rating__c').getDescribe().fields.getMap();
            
            for(String fldName: fldList1){
                if(!fieldMap1.get(fldName).getDescribe().isAccessible()){
                    readAccess = false;
                }                           
            }
            
                    
            cr();
            crDisplay();
       
       /*filters*/
        label1 = ApexPages.currentPage().getParameters().get('labelOne');
        label2 = ApexPages.currentPage().getParameters().get('labelTwo');
        label3 = ApexPages.currentPage().getParameters().get('labelThree');
        selectedLevel1 = ApexPages.currentPage().getParameters().get('selectOne');
        selectedLevel2 = ApexPages.currentPage().getParameters().get('selectTwo');
        selectedLevel3 = ApexPages.currentPage().getParameters().get('selectThree');
        
        List<AggregateResult> asperm = [SELECT count(Id) c FROM PermissionSetAssignment WHERE AssigneeId = :Userinfo.getUserId() AND PermissionSet.Name = 'Funnel_App_Setup'];
        if((asperm != null && asperm.size() > 0 && asperm[0].get('c') != null && (Integer)asperm[0].get('c') > 0)   ){
            adminPer= true;
        }else{
            adminPer= false;
        }
        
        isManger = FunnelTriggerBatchHelper.isManager(UserInfo.getUserId());
        
        /*
        managemenetReports = new Map<String,String>();
        
        User u = [SELECT Name, UserPreferencesLightningExperiencePreferred FROM User WHERE id = :UserInfo.getUserId()];
        
        List<String> dashList = new List<String>();
        dashList.add('mXaDybYGcSDujlyIRRJQxUrUEqXiFe');
        
        managemenetReports = FunnelNavigationHelper.fetchDashboards(dashList,u);*/
        
    }
        catch(Exception ex){
            System.debug('Exception occured: '+ ex+' Line number: '+ex.getLineNumber());
            FunnelTriggerBatchHelper.sendErrorMail(' FunnelAssignRoleController '+ex.getMessage()+' '+ex.getStackTraceString()+ ' line number: '+ex.getLineNumber()+' cause '+ex.getCause());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage()));
        } 
    }
    string defaultRole;
    Map<Id,Certification_Rating__c> mapCerts = new Map<Id,Certification_Rating__c>();
    
     public List<SelectOption>  getRole() {
       
           List<SelectOption> Options = new List<SelectOption>();
           
           //Schema.DescribeFieldResult statusFieldDescription = FunnelMetrics__Certification_Rating__c.Roles_enabled__c.getDescribe();
           Schema.DescribeFieldResult statusFieldDescription = Certification_Rating__c.Roles_enabled__c.getDescribe();
         
           for (Schema.Picklistentry picklistEntry : statusFieldDescription.getPicklistValues())
           {
               Options.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
           }
           defaultRole= string.valueOf(options[0].getvalue());
           system.debug('defaultRole---' +defaultRole);
           return Options ;
    }
           
    public void cr(){
       
        cwList = new list<certificateWrapper>();
        certificate = new list<Certification_Rating__c>();
        if(readAccess){    
        
             List<Certification_Rating__c> cc = [Select id, Name,User_Type__c,Roles_enabled__c,Weight__c,Timing__c,Description__c,Calculation_type__c,Assessment_type__c, Category__c from Certification_Rating__c WHERE Deactivated__c = false AND SRP_Field_Name__c !=null  ORDER BY Category__c DESC,Display_Order__c ASC, CreatedDate DESC];   
             certificate.addAll(cc);
             cc.clear();
             
             cc = [Select id, Name,User_Type__c,Roles_enabled__c,Weight__c,Timing__c,Description__c,Calculation_type__c,Assessment_type__c, Category__c from Certification_Rating__c WHERE Deactivated__c = false  AND SRP_Field_Name__c =null  ORDER BY Category__c DESC,Display_Order__c ASC, CreatedDate DESC];   
             certificate.addAll(cc);
             
            for(Certification_Rating__c c : certificate ){
            system.debug('c--'+c);
            Set<String> rolesSet = new Set<String>();
            
                if(c.Roles_enabled__c != null){
                    List<String> rolesList = c.Roles_enabled__c.split(';');
                    for(String r:rolesList){
                        rolesSet.add(r);
                    }
                }
            certificateWrapper cW = new certificateWrapper();
            //cw.certificateRating  = new Certification_Rating__c();
            if( (c.Roles_enabled__c != null  && selectedValue != null && rolesSet.contains(selectedValue)) || c.Assessment_type__c== 'Quantitative' ){
                cW.certificateRating  = c;
                cW.isSelected = true;
            }else{
                cW.certificateRating= c;
                cW.isSelected = false;
            }
            cwList.add(cw);
            mapCerts.put(c.id,c);
        }
            crDisplay();
        }
    }
   
    public void crDisplay(){
       
       if(readAccess){ 
        certificateDisplay = new List<Certification_Rating__c> ();
        List<Certification_Rating__c> cc=[Select id, Name,User_Type__c ,Roles_enabled__c,Weight__c,Timing__c,Description__c,Calculation_type__c,Assessment_type__c, Category__c from Certification_Rating__c   where  ( Roles_enabled__c includes (:selectedValue) OR Assessment_type__c='Quantitative') AND Deactivated__c = false AND SRP_Field_Name__c !=null ORDER BY Category__c DESC,Display_Order__c ASC, CreatedDate DESC];
        certificateDisplay.addAll(cc); 
        cc.clear();
        cc= [Select id, Name,User_Type__c ,Roles_enabled__c,Weight__c,Timing__c,Description__c,Calculation_type__c,Assessment_type__c, Category__c from Certification_Rating__c   where  ( Roles_enabled__c includes (:selectedValue) OR Assessment_type__c='Quantitative') AND Deactivated__c = false AND SRP_Field_Name__c =null ORDER BY Category__c DESC,Display_Order__c ASC, CreatedDate DESC  ];
        certificateDisplay.addAll(cc); 

        if(certificateDisplay.size() > 0 && credit != true){
            crDisplaypanel = true;
            crpanel = false;
            system.debug('DISPLAY__');
        }else{
            crDisplaypanel = false;
            crpanel = true;
            system.debug('EDIT__');
        }
       }
    }      
           
    public void editCerti(){
        crDisplaypanel = false;
        crpanel = true;
        credit = true;
    }  

    public void updatecerti(){
        
        try{
            
            list<Certification_Rating__c> updateCertificate = new list<Certification_Rating__c>();
            
            List<String> fldList1 = new List<String>{prefix+'Roles_enabled__c'};
                
            Boolean updateAccess = true;
                        
            Map <String, Schema.SObjectField> fieldMap1 = Schema.getGlobalDescribe().get(prefix+'Certification_Rating__c').getDescribe().fields.getMap();
            
            for(String fldName: fldList1){
                if(!fieldMap1.get(fldName).getDescribe().isUpdateable()){
                  ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Insufficient access'));
                  updateAccess = false;
                }                           
            }
            
            if(updateAccess){
            
                for(certificateWrapper c : cwList){
                   
                    Certification_Rating__c updateCerti;
                    
                    updateCerti = mapCerts.get(c.certificateRating.id);
                    
                    if(c.isSelected){
                        if(!checkcontain(c.certificateRating.Roles_enabled__c,selectedValue)){
                            if(c.certificateRating.Roles_enabled__c != null){
                                c.certificateRating.Roles_enabled__c = c.certificateRating.Roles_enabled__c+';'+selectedValue ; 
                            }else{
                                c.certificateRating.Roles_enabled__c = selectedValue ; 
                            }
                            
                        }
                    }else{
                        if(checkcontain(c.certificateRating.Roles_enabled__c,selectedValue)){
                           
                            c.certificateRating.Roles_enabled__c  = c.certificateRating.Roles_enabled__c.replaceAll(';?'+selectedValue +'?','');
                        }
                    }
                    //updateCerti.id=c.certificateRating.id;
                    updateCerti.Roles_enabled__c  =c.certificateRating.Roles_enabled__c ;
                    updateCertificate.add(updateCerti); 
                }
            }
            else{
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Insufficient access'));
            }
            
            system.debug('updateCertificate ---'+updateCertificate );
           
       if(Schema.getGlobalDescribe().get(prefix+'Certification_Rating__c').getDescribe().isUpdateable()){ 
               update updateCertificate ;
           }
           else{
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Insufficient access'));
           }
           
           // crDisplaypanel = true;
           // crpanel = false;
            credit = false;
            cr();
            ansCreDel();
        }
        catch(Exception ex){
            System.debug('Exception occured: '+ ex+' Line number: '+ex.getLineNumber());
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage()));
            FunnelTriggerBatchHelper.sendErrorMail(' FunnelAssignRoleController '+ex.getMessage()+' '+ex.getStackTraceString()+ ' line number: '+ex.getLineNumber()+' cause '+ex.getCause());
        } 
    }
    
    public void ansCreDel(){
        List<Sales_Rep_Profile__c> srplist = [Select id from Sales_Rep_Profile__c where Active__c = true];
        if(srplist != null && srplist.size() > 0){
            Set<Id> profsForAnsCreation = new Set<Id>();
            for(Sales_Rep_Profile__c s : srplist ){
                profsForAnsCreation.add(s.id);
            }
             FunnelCreateCertAnswers_Controller.deleteAndCreateCertAnswers(profsForAnsCreation,profsForAnsCreation);    
        }
    
    }
    
    public boolean checkcontain(string ro, string cp){
        list<string> str = new list<string>();
        boolean f ;
        system.debug('ro---'+ro);
        if(ro != null){
           str =  ro.split(';');
            if(str.contains(cp)){
                f = true;
            }else{
                f= false;
            } 
        }else{
                f= false;
        }
        
        return f;
    }
    
    /*Navigation*/
    //Method called on clicking on View Scoring Dashboard
    public PageReference navigateToCertification(){
        
        return FunnelNavigationHelper.navigateToCertification(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
    
    //Method called on clicking on View Scoring Dashboard
    public PageReference navigateToDashboard(){
        
        return FunnelNavigationHelper.navigateToDashboard(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
    
    //Method called on clicking Performance Dashboard on header
    public PageReference navigateToCalculator(){
        
        return FunnelNavigationHelper.navigateToCalculator(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
        
    }
    
    //Method called on clicking Home on header    
    public PageReference navigateToHomePage(){
        
       return FunnelNavigationHelper.navigateToHomePage(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
        
    }
    
    //Method called on clicking Reporting on header    
    public PageReference navigateToReportsPage(){
        
        return FunnelNavigationHelper.navigateToReportsPage(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
        
    }
    
    //Method called on clicking App Setup on header    
    public PageReference navigateToAppSetup(){
        
        return FunnelNavigationHelper.navigateToAppSetupPage(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
        
    }
    public PageReference navigateToCertificateReports(){
        
        return FunnelNavigationHelper.navigateToCertificateReports(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
        
    } 
    
    public PageReference navigateToRatings(){
        
        return FunnelNavigationHelper.navigateToCreateEditRatings(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
        
    }  
    public PageReference navigateToCustomMetric(){
        
        return FunnelNavigationHelper.navigateToCustomMetric(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);    
    
    }
    public PageReference navigateToNotifications(){
        
        return FunnelNavigationHelper.navigateToNotifications(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    }
    
    public PageReference navigateToCategories(){
        
        return FunnelNavigationHelper.navigateToCategories(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    }
    
    public PageReference navigateToAnalytics(){
        
        return FunnelNavigationHelper.navigateToAnalytics(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
    
    public PageReference navigateToFunnelAnalyticQualitative(){
        
        return FunnelNavigationHelper.navigateToFunnelAnalyticQualitative(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
    
    public PageReference navigateToFunnelAnalytic(){
        
        return FunnelNavigationHelper.navigateToFunnelAnalytic(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
    
     public PageReference navigateToFunnelEvaluationGuidelines(){
        
        return FunnelNavigationHelper.navigateToFunnelEvaluationGuidelines(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
    public PageReference navigateToAnnualizationDashboard(){
        
        return FunnelNavigationHelper.navigateToFunnelAnnualizationDashboard(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
     public PageReference navigateToFunnelSetup(){
        
        return FunnelNavigationHelper.navigateToFunnelSetup(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
    
    public PageReference navigateToFunnelReviewGoals(){
        
        return FunnelNavigationHelper.navigateToFunnelReviewGoals(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
    public PageReference navigateToFunnelManagerUpdate(){
        
        return FunnelNavigationHelper.navigateToFunnelManagerUpdate(label1,label2,label3,selectedLevel1,selectedLevel2,selectedLevel3);
    
    }
    /*Navigation*/
    

}