force-app/main/default/objects/Certification_Answer__c/Certification_Answer__c.object-meta.xml
<CustomObject>
    <description>Used to store the ratings given to the sales rep</description>
    <label>Certification Answer</label>
    <nameField>
        <label>Certification Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification_Answer__c/fields/Sales_Rep_Profile__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the sales profile the answer record is associated with</description>
    <label>Sales Rep Profile</label>
    <referenceTo>Sales_Rep_Profile__c</referenceTo>
    <relationshipLabel>Certification Answers</relationshipLabel>
    <relationshipName>Certification_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Level__c/Company_Level__c.object-meta.xml
<CustomObject>
    <description>Stores the levels of the company and the corresponding sales profile who heads the level</description>
    <label>Company Level</label>
    <nameField>
        <displayFormat>L-{000}</displayFormat>
        <label>Company Levels Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Levels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company_Level__c/fields/Sales_Rep_Profile__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores the sales rep profile the particular level value is associated with</description>
    <label>Sales Rep Profile</label>
    <referenceTo>Sales_Rep_Profile__c</referenceTo>
    <relationshipLabel>Company Levels</relationshipLabel>
    <relationshipName>Company_Levels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification_Setting__c/Notification_Setting__c.object-meta.xml
<CustomObject>
    <label>Notification Setting</label>
    <nameField>
        <label>Notification Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notification Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Setting__c/fields/Advance_Reminders__c.field-meta.xml
<CustomField>
    <fullName>Advance_Reminders__c</fullName>
    <label>Advance Notice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3 days prior</fullName>
            </value>
            <value>
                <fullName>7 days prior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Setting__c/fields/Enable_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Enable_Notifications__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Notifications</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification_Setting__c/fields/Escalation__c.field-meta.xml
<CustomField>
    <fullName>Escalation__c</fullName>
    <label>Escalation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2 days overdue</fullName>
            </value>
            <value>
                <fullName>7 days overdue</fullName>
            </value>
            <value>
                <fullName>10 days overdue</fullName>
            </value>
            <value>
                <fullName>Never</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Setting__c/fields/Notification_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Notification_Frequency__c</fullName>
    <label>Notification Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Every Other Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

funnelocity/src/objects/Sales_Rep_Profile__c.object
<CustomObject>
    <description>Object used to store the details of every person in the sales team</description>
    <fields>
        <fullName>Month_1_Quota_Amount__c</fullName>
        <description>Rep&apos;s Quota for Month 1</description>
        <label>Month 1 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X12_Month_Opprties_Added_to_the_funnel__c</fullName>
        <description>Number of opportunities added to the sales profile for the past 12 months</description>
        <label>12 Month Opprties Added to the funnel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>X12_Month_Rolling_Average_Sales_Cycle__c</fullName>
        <description># of days between becoming an opp and close/won for the past 12 months</description>
        <label>12 Month Rolling Average Sales Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YTD_Revenue__c</fullName>
        <description>Sum of Revenue from won opportunities YTD (calendar/fiscal year configured during the app setup is considered) for sales rep</description>
        <label>YTD Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Rep Profile</label>
    <nameField>
        <label>Sales Rep Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/Quarterly_Lead_Added__c.field-meta.xml
<CustomField>
    <fullName>Quarterly_Lead_Added__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quarterly Lead Added</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/Quarterly_Opportunities_added_to_Qualifi__c.field-meta.xml
<CustomField>
    <fullName>Quarterly_Opportunities_added_to_Qualifi__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quarterly Opportunities added to Qualifi</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/Quarterly_Quota_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Quarterly_Quota_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quarterly Quota Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile__c/fields/X12_Month_Average_Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Average_Selling_Price__c</fullName>
    <description>12 month revenue / 12 month opptys won</description>
    <formula>IF(X12_Month_Rolling_Opptys_Won__c &gt; 0, X12_Month_Rolling_Revenue__c / X12_Month_Rolling_Opptys_Won__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>12 Month Average Selling Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/Sales_Rep_Profile_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Store Sales Rep Profile Snapshot</description>
    <label>Sales Rep Profile Snapshot</label>
    <nameField>
        <label>Sales Rep Profile Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Rep Profile Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/Month_1_Quota_Amount__c.field-meta.xml
<CustomField>
    <fullName>Month_1_Quota_Amount__c</fullName>
    <label>Month 1 Quota Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/Quarterly_Lead_Added__c.field-meta.xml
<CustomField>
    <fullName>Quarterly_Lead_Added__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quarterly Lead Added</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/Quarterly_Opportunities_added_to_Qualifi__c.field-meta.xml
<CustomField>
    <fullName>Quarterly_Opportunities_added_to_Qualifi__c</fullName>
    <label>Quarterly Opportunities added to Qualifi</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/Quarterly_Quota_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Quarterly_Quota_Revenue__c</fullName>
    <label>Quarterly Quota Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/Sales_Rep_Profile__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep Profile</label>
    <referenceTo>Sales_Rep_Profile__c</referenceTo>
    <relationshipLabel>Sales Rep Profile Snapshots (Sales Rep Profile)</relationshipLabel>
    <relationshipName>Sales_Rep_Profile_Snapshots1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/X12_Month_Average_Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Average_Selling_Price__c</fullName>
    <label>12 Month Average Selling Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/X12_Month_Rolling_Average_Sales_Cycle__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Rolling_Average_Sales_Cycle__c</fullName>
    <label>12 Month Rolling Average Sales Cycle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/X12_Month_Rolling_Opportunity_Close_Rate__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Rolling_Opportunity_Close_Rate__c</fullName>
    <label>12 Month Rolling Opportunity Close Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sales_Rep_Profile_Snapshot__c/fields/YTD_Revenue__c.field-meta.xml
<CustomField>
    <fullName>YTD_Revenue__c</fullName>
    <label>YTD Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

funnelocity/src/objects/YTD_Quota_Revenue__c.object
<CustomObject>
    <description>The object stores the data that is re-calculated for every fiscal year</description>
    <fields>
        <fullName>Month_1_Quota_Amount__c</fullName>
        <description>Stores the quota amount for the first month of the fiscal year</description>
        <label>Month 1 Quota Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the sales rep profile to which the quota/revenue record is associated</description>
        <label>Sales Rep Profile</label>
        <referenceTo>Sales_Rep_Profile__c</referenceTo>
        <relationshipLabel>YTD Quota/Revenues</relationshipLabel>
        <relationshipName>YTD_Quota_Revenues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YTD_Revenue__c</fullName>
        <description>Sum of Revenue from won opportunities in the current fiscal year</description>
        <label>YTD Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>YTD Quota/Revenue</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>YTD Quota/Revenue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>YTD Quota/Revenues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/YTD_Quota_Revenue__c/fields/X12_Month_Average_Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Average_Selling_Price__c</fullName>
    <label>12 Month Average Selling Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/YTD_Quota_Revenue__c/fields/X12_Month_Rolling_Average_Sales_Cycle__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Rolling_Average_Sales_Cycle__c</fullName>
    <label>12 Month Rolling Average Sales Cycle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/YTD_Quota_Revenue__c/fields/X12_Month_Rolling_Opportunity_Close_Rate__c.field-meta.xml
<CustomField>
    <fullName>X12_Month_Rolling_Opportunity_Close_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>12 Month Rolling Opportunity Close Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/FunnelPostApisTest.cls
@isTest
public class FunnelPostApisTest {
    
    //static testmethod void testAccess() {           
        
        /*               
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
        UserRole r = new UserRole(DeveloperName = 'MyCustomRole', Name = 'My Role');
        insert r;
         
        FunnelDataFactory.FunnelTestWrapper fw = new FunnelDataFactory.FunnelTestWrapper();
        fw.index = 1;
        fw.profileId = profileId;        
        fw.userRoleId = r.id;
        
        List<User> us = FunnelDataFactory.createUser(fw,1);
        insert us;
        User u = us[0];
        
        fw = new FunnelDataFactory.FunnelTestWrapper();
        fw.index = 2;
        fw.profileId = profileId;        
        fw.userRoleId = r.id;
        us = FunnelDataFactory.createUser(fw,1);
        insert us;
        User u2 = us[0];
        
        fw = new FunnelDataFactory.FunnelTestWrapper();
        fw.index = 3;
        fw.profileId = profileId;        
        fw.userRoleId = r.id;
        us = FunnelDataFactory.createUser(fw,1);
        insert us;
        User u3 = us[0];
        
        fw = new FunnelDataFactory.FunnelTestWrapper();
        fw.index = 4;
        fw.profileId = profileId;        
        fw.userRoleId = r.id;
        us = FunnelDataFactory.createUser(fw,1);
        insert us;
        User u4 = us[0];
        
        fw = new FunnelDataFactory.FunnelTestWrapper();
        fw.index = 5;
        fw.profileId = profileId;        
        fw.userRoleId = r.id;
        us = FunnelDataFactory.createUser(fw,1);
        insert us;
        User u5 = us[0];
        
        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'FunnelReadAccessAllObjs'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id );         
        
        
        system.runAs(u){
            
            test.startTest();
            List<Sales_Rep_Profile__c > splist= new List<Sales_Rep_Profile__c >();
            
            Fiscal_Year_Setting__c fiscalYr = FunnelDataFactory.setFiscalYear(System.Today()-1);
            insert fiscalYr;
            
            Notification_Setting__c  noti = new Notification_Setting__c (Enable_Notifications__c = true,Advance_Reminders__c = '1 day prior',Notification_Frequency__c = 'Daily', Escalation__c ='Never');
            insert noti ;
            
            fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.index = 4;
            fw.userId = u4.id;
            system.debug(' fw.userId '+fw.userId);
            Sales_Rep_Profile__c spMgrMgr = FunnelDataFactory.createSalesRep(fw);
            insert spMgrMgr;
            splist.add(spMgrMgr);
            
            fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.index = 1;
            fw.userId = u.id;
            fw.salesMgr = spMgrMgr.id;
            system.debug(' fw.userId '+fw.userId);
            Sales_Rep_Profile__c spMgr = FunnelDataFactory.createSalesRep(fw);
            insert spMgr;
            splist.add(spMgr);
            
            fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.index = 5;
            fw.userId = u5.id;
            fw.salesMgr = spMgrMgr.id;
            system.debug(' fw.userId '+fw.userId);
            Sales_Rep_Profile__c spMgr2 = FunnelDataFactory.createSalesRep(fw);
            insert spMgr2;
            splist.add(spMgr2);
            
            fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.index = 2;        
            fw.userId = u2.id;
            fw.salesMgr = spMgr.id;
            system.debug(' fw.userId '+fw.userId);        
            Sales_Rep_Profile__c spProf = FunnelDataFactory.createSalesRep(fw);
            spProf.Quarterly_Opportunities_added_to_Qualifi__c = 5;
            spProf.Quarterly_Lead_Added__c = 5;
            spProf.Quarterly_Quota_Revenue__c = 500;
            spProf.Month_1_Quota_Amount__c= 500;
            spProf.YTD_Revenue__c = 500;
            spProf.X12_Month_Rolling_Opportunity_Close_Rate__c = 50;
            insert spProf;
            splist.add(spProf);
            
            fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.index = 3;        
            fw.userId = u3.id;
            fw.salesMgr = spMgr.id;
            system.debug(' fw.userId '+fw.userId);        
            Sales_Rep_Profile__c spProf1 = FunnelDataFactory.createSalesRep(fw);
            spProf1.Quarterly_Opportunities_added_to_Qualifi__c = 5;
            spProf1.Quarterly_Lead_Added__c = 5;
            spProf1.Quarterly_Quota_Revenue__c = 500;
            spProf1.Month_1_Quota_Amount__c= 500;
            spProf1.YTD_Revenue__c = 500;
            spProf1.X12_Month_Rolling_Opportunity_Close_Rate__c = 50;
            insert spProf1;
            splist.add(spProf1);
            
            List<YTD_Quota_Revenue__c> yrq = FunnelDataFactory.createPriorYearResult(splist);   
            
            yrq[3].YTD_Revenue__c = 200;
            yrq[3].X12_Month_Rolling_Average_Sales_Cycle__c = 20;
            yrq[3].X12_Month_Average_Selling_Price__c = 200;
            yrq[3].X12_Month_Opprties_Added_to_the_funnel__c = 20;
            yrq[3].X12_Month_Leads_Added__c = 35;
            
            yrq[4].YTD_Revenue__c = 200;
            yrq[4].X12_Month_Rolling_Average_Sales_Cycle__c = 20;
            yrq[4].X12_Month_Average_Selling_Price__c = 200;
            yrq[4].X12_Month_Opprties_Added_to_the_funnel__c = 20;
            yrq[4].X12_Month_Leads_Added__c = 35;           
            
            insert yrq;
            
            fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.index = 1;  
            fw.levelName = 'Country';
            fw.levelValue = 'US';
            fw.salesProfForCompLevel = spMgr.id;
            
            List<Sales_Rep_Profile__c> sp = new List<Sales_Rep_Profile__c>();
            sp.add(spMgr);
            List<Company_Level__c> cl = FunnelDataFactory.createCompanyLevel(fw,sp);                        
            insert cl;
            
            fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.index = 2;  
            fw.levelName = 'Country';
            fw.levelValue = 'Canada';
            fw.salesProfForCompLevel = spMgr2.id;
            
            sp = new List<Sales_Rep_Profile__c>();
            sp.add(spMgr2);
            cl = FunnelDataFactory.createCompanyLevel(fw,sp);                        
            insert cl;
            
            fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.index = 3;  
            fw.levelName = 'Company';
            fw.levelValue = 'Funnel Metrics';
            fw.salesProfForCompLevel = spMgrMgr.id;
            
            sp = new List<Sales_Rep_Profile__c>();
            sp.add(spMgrMgr);
            cl = FunnelDataFactory.createCompanyLevel(fw,sp);                        
            insert cl;
                                    
            FunnelCalculator fc = new FunnelCalculator();
            system.assertEquals(fc.fcw7.Resultstring,'$1,000');
            test.stopTest();
            
        //}
        
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/claimApi'; 
        req.params.put('phoneNumber', '9876543210');
        req.params.put('claimNumber', '111111');
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;                 
        
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                 'Complete',
                                                 '[{"Name": "sForceTest1"}]',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        FunnelPostApis fp = new FunnelPostApis();
        fp.getAccessToken();
            
        system.assert(fp.msg != '');*/
                                    
    //}
    
    
    static testMethod void createCustomerTest(){
        
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/claimApi'; 
        req.params.put('phoneNumber', '9876543210');
        req.params.put('claimNumber', '111111');
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;                 
        
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                 'Complete',
                                                 '[{"Name": "sForceTest1"}]',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        FunnelPostApis fp = new FunnelPostApis();
        fp.createCustomer();
        system.assert(fp.msg != null);
        Test.stopTest(); 
    
    }        
    
    static testMethod void createQualRatingTest(){
        
        FunnelDataFactory.FunnelTestWrapper fw = new FunnelDataFactory.FunnelTestWrapper();
        fw.type = 'Qualitative';   
        fw.calcType = 'Y/N';
        fw.category = 'Test category';            
        fw.userType = 'Tenured';
        fw.timing = 'End of month';
        fw.weight = '4';      
        
        DescribeFieldResult describe = Sales_Rep_Profile__c.Role__c.getDescribe();
        List<PicklistEntry> availableValues = describe.getPicklistValues();
        String val = availableValues[0].getValue();
                               
        fw.rolesEnabled = val;          
        List<Certification_Rating__c> ratings = FunnelDataFactory.createCertificationRatings(fw,4);
        ratings[0].Timing__c = 'End of quarter';
        ratings[1].Timing__c = 'Bi-annual';
        ratings[2].Timing__c = 'Annual';
                                
        insert ratings;
                
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/claimApi'; 
        req.params.put('phoneNumber', '9876543210');
        req.params.put('claimNumber', '111111');
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;                 
        
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                 'Complete',
                                                 '[{"Name": "sForceTest1"}]',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        FunnelPostApis fp = new FunnelPostApis();
        fp.createQualRating();
        system.assert(fp.msg != null);
        Test.stopTest(); 
    
    }
    
    
    static testMethod void createQuantRatingTest(){
        
        FunnelDataFactory.FunnelTestWrapper fw = new FunnelDataFactory.FunnelTestWrapper();
        fw.type = 'Quantitative';   
        fw.calcType = 'Y/N';
        fw.category = 'Test category';            
        fw.userType = 'Tenured';
        fw.timing = 'End of month';
        fw.weight = '4';      
        
        DescribeFieldResult describe = Sales_Rep_Profile__c.Role__c.getDescribe();
        List<PicklistEntry> availableValues = describe.getPicklistValues();
        String val = availableValues[0].getValue();
                               
        fw.rolesEnabled = val;          
        List<Certification_Rating__c> ratings = FunnelDataFactory.createCertificationRatings(fw,4);
        ratings[0].Timing__c = 'End of quarter';
        ratings[1].Timing__c = 'Bi-annual';
        ratings[2].Timing__c = 'Annual';
                                
        insert ratings;
        
        Test.startTest();
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/claimApi'; 
        req.params.put('phoneNumber', '9876543210');
        req.params.put('claimNumber', '111111');
        req.httpMethod = 'POST';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res;                 
        
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                 'Complete',
                                                 '[{"Name": "sForceTest1"}]',
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        FunnelPostApis fp = new FunnelPostApis();
        fp.createQuantRating();
        system.assert(fp.msg != null);
        Test.stopTest(); 
    
    }
    
    
    static testMethod void createQualMetricTest(){
        
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;                        
        
        UserRole r = new UserRole(DeveloperName = 'MyCustomRole' , Name = 'My Role');
        insert r;
        
        FunnelDataFactory.FunnelTestWrapper fw = new FunnelDataFactory.FunnelTestWrapper();
        fw.profileId = profileId;
        fw.index = 1;
        fw.userRoleId = r.id;
        
        List<User> userList = FunnelDataFactory.createUser(fw,100);
        insert userList;
        
        System.runAs (userList[0]) { 
            
            Fiscal_Year_Setting__c fiscalYr = FunnelDataFactory.setFiscalYear(System.Today()-1);
            insert fiscalYr;
                           
            
            system.debug(userList);
            
            List<Sales_Rep_Profile__c> sp = FunnelDataFactory.createSalesReplist(userList);
            insert sp;
            
            system.debug(sp);
            
            fw = new FunnelDataFactory.FunnelTestWrapper();
            fw.type = 'Qualitative';   
            fw.calcType = 'Y/N';
            fw.category = 'Test category';            
            fw.userType = 'Tenured';
            fw.timing = 'End of month';
            fw.weight = '4';      
            
            DescribeFieldResult describe = Sales_Rep_Profile__c.Role__c.getDescribe();
            List<PicklistEntry> availableValues = describe.getPicklistValues();
            String val = availableValues[0].getValue();
                                   
            fw.rolesEnabled = val;          
            List<Certification_Rating__c> ratings = FunnelDataFactory.createCertificationRatings(fw,4);
            ratings[0].Timing__c = 'End of quarter';
            ratings[1].Timing__c = 'Bi-annual';
            ratings[2].Timing__c = 'Annual';
                                    
            insert ratings;
            
            List<Certification_Answer__c> ans = FunnelDataFactory.createCertificationAnswers(fw,ratings);
            for(Certification_Answer__c a: ans){
                a.Rating_start_date__c = Date.today() - 4;
                a.Due_Date__c = Date.today();
            }
            
            ans[3].Rating_Score__c = 4;
            insert ans;
                
            Test.startTest();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
            req.requestURI = '/services/apexrest/claimApi'; 
            req.params.put('phoneNumber', '9876543210');
            req.params.put('claimNumber', '111111');
            req.httpMethod = 'POST';
            req.addHeader('Content-Type', 'application/json'); 
            RestContext.request = req;
            RestContext.response = res;                 
            
            SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                     'Complete',
                                                     '[{"Name": "sForceTest1"}]',
                                                     null);
            Test.setMock(HttpCalloutMock.class, fakeResponse);
            
            FunnelPostApis fp = new FunnelPostApis();
            fp.dtSnapShot = Date.today();
            fp.createQualMetric(sp);
            
            system.assert(fp.msg != null);
            Test.stopTest();
        }                
    
    }
    
    static testMethod void createQuantMetricTest(){
        
        FunnelDataFactory.FunnelTestWrapper fw1 = new FunnelDataFactory.FunnelTestWrapper();
        fw1.index = 1;   
        fw1.ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;                
        UserRole r1 = new UserRole(DeveloperName = 'MyCustomRole0A'+fw1.index , Name = 'My Role'+fw1.index);
        
        List<User> userList1 = FunnelDataFactory.createUser(fw1,1);        
        insert userList1;
        
        System.runAs (userList1[0]) { 
        
            List<Sales_Rep_Profile__c> ss = FunnelDataFactory.createSalesReplist(userList1);
            system.debug(' ss '+ss); 
            insert ss;
            
            List<Sales_Rep_Profile_Snapshot__c> spsnap = FunnelDataFactory.createSalesReplistSnapshot(ss);
            
            for(Sales_Rep_Profile_Snapshot__c s: spsnap){    
               s.Snapshot_Scheduled_Date__c = Date.today();
               system.debug(' ss[0].id '+ss[0].id);
               s.Sales_rep_profile__c = ss[0].id;
               s.YTD_Quota__c = 1000;
            }
            insert spsnap;
                     
            Test.startTest();                
            
            system.debug(' spsnap '+spsnap[0].Sales_rep_profile__c);
            
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
            req.requestURI = '/services/apexrest/claimApi'; 
            req.params.put('phoneNumber', '9876543210');
            req.params.put('claimNumber', '111111');
            req.httpMethod = 'POST';
            req.addHeader('Content-Type', 'application/json'); 
            RestContext.request = req;
            RestContext.response = res;                 
            
            SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                     'Complete',
                                                     '[{"Name": "sForceTest1"}]',
                                                     null);
            Test.setMock(HttpCalloutMock.class, fakeResponse);
            
            FunnelPostApis fp = new FunnelPostApis();
            fp.dtSnapShot = Date.today();
            fp.createQuantMetric(ss);
            
            system.assert(fp.msg != null);
            Test.stopTest();     
        }           
    
    }
    
    public class SingleRequestMock implements HttpCalloutMock {
        protected Integer code;
        protected String status;
        protected String bodyAsString;
        protected Blob bodyAsBlob;
        protected Map<String, String> responseHeaders;

        public SingleRequestMock(Integer code, String status, String body,
                                         Map<String, String> responseHeaders) {
            this.code = code;
            this.status = status;
            this.bodyAsString = body;
            this.bodyAsBlob = null;
            this.responseHeaders = responseHeaders;
        }

        public SingleRequestMock(Integer code, String status, Blob body,
                                         Map<String, String> responseHeaders) {
            this.code = code;
            this.status = status;
            this.bodyAsBlob = body;
            this.bodyAsString = null;
            this.responseHeaders = responseHeaders;
        }

        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse resp = new HttpResponse();
            resp.setStatusCode(code);
            resp.setStatus(status);
            if (bodyAsBlob != null) {
                resp.setBodyAsBlob(bodyAsBlob);
            } else {
                resp.setBody(bodyAsString);
            }

            if (responseHeaders != null) {
                 for (String key : responseHeaders.keySet()) {
                resp.setHeader(key, responseHeaders.get(key));
                 }
            }
            return resp;
        }
    }
    
}